# dbt Project Configuration for sf_user Pipeline
name: 'sf_user_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'sf_user_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  sf_user_pipeline:
    # Global Iceberg configuration for all models
    +file_format: iceberg
    +table_properties:
      write.format.default: parquet
      write.parquet.compression-codec: snappy
      write.metadata.compression-codec: gzip
      write.target-file-size-bytes: 134217728  # 128MB target file size
      
    # Staging models configuration
    staging:
      +materialized: view
      +schema: staging
      
    # Intermediate models configuration  
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
      
    # Marts/dimension models configuration
    marts:
      +materialized: incremental
      +incremental_strategy: merge
      +on_schema_change: sync_all_columns
      +schema: curated
      
      # SCD-specific configurations
      scd:
        +unique_key: _scd_id
        +merge_update_columns: ['is_current', '_dbt_updated_at']
        +incremental_predicates: ["lastmodifieddate > (select coalesce(max(update_date), '1900-01-01') from {{ this }})"]

# Snapshot configurations
snapshots:
  sf_user_pipeline:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: lastmodifieddate
    +file_format: iceberg

# Test configurations
tests:
  sf_user_pipeline:
    +severity: warn  # Default test severity
    
# Seed configurations
seeds:
  sf_user_pipeline:
    +file_format: iceberg
    +schema: seeds

# Documentation
docs:
  generate: true
  
# Variables for the project
vars:
  # SCD Type 2 configuration
  scd_tracked_fields: ['division', 'audit_phase__c']
  
  # Data quality thresholds
  max_records_per_batch: 50000
  data_quality_threshold: 0.95
  
  # Business rules
  valid_divisions: ['North', 'South', 'East', 'West', 'Central']
  valid_audit_phases: ['Phase1', 'Phase2', 'Phase3', 'Complete']
  
  # Date ranges for testing
  test_start_date: '2024-01-01'
  test_end_date: '2024-12-31'