# dbtHub Configuration for Salesforce sf_user Extraction
version: "1.0"

settings:
  project_name: "sf_user_pipeline"
  log_level: "INFO"
  
sources:
  - name: salesforce_production
    type: salesforce
    description: "Salesforce sf_user extraction"
    
    connection:
      credentials_source: aws_secrets_manager
      secret_name: "salesforce/production/credentials"
      region: "us-east-1"
      api_version: "58.0"
      
    destination:
      type: iceberg
      catalog: glue_catalog
      database: sf_raw
      s3_location: "s3://lumata-lakehouse-raw/sf_raw/"
      table_properties:
        write.format.default: parquet
        write.parquet.compression-codec: snappy
    
    tables:
      - name: sf_user
        identifier: User
        destination_table: sf_user
        description: "Salesforce User object with SCD tracking"
        
        loading_strategy:
          type: incremental
          strategy: merge
          unique_key: Id
          updated_at: LastModifiedDate
          lookback_window: "1 hour"
          batch_size: 10000
          
        columns:
          - name: Id
            type: string
            description: "Salesforce User ID"
            required: true
            
          - name: Name
            type: string
            description: "User full name"
            required: true
            
          - name: Division
            type: string
            description: "User division (SCD tracked)"
            required: false
            
          - name: Audit_Phase__c
            type: string
            description: "Audit phase (SCD tracked)"
            required: false
            
          - name: LastModifiedDate
            type: timestamp
            description: "Last modified timestamp"
            required: true
            
          - name: IsActive
            type: boolean
            description: "User active status"
            required: true
            
          - name: IsDeleted
            type: boolean
            description: "User deleted status"
            required: true
            
          - name: CreatedDate
            type: timestamp
            description: "Creation timestamp"
            required: true
            
        data_quality:
          required_fields: ["Id", "Name", "LastModifiedDate"]
          unique_fields: ["Id"]
          
        filters:
          - field: IsDeleted
            operator: "="
            value: false

error_handling:
  salesforce_api:
    max_retries: 3
    timeout_seconds: 300
    
  data_quality:
    on_schema_change: warn_and_continue
    quarantine_invalid_records: true
    quarantine_table: sf_raw.sf_user_quarantine

monitoring:
  enable_metrics: true
  metrics_destination: cloudwatch
  
scheduling:
  default_schedule: "0 */6 * * *"  # Every 6 hours